update 241204
blueblur0730/modified-plugins pull request #17
Opened 2024-12-04 06:37 UTC by Majestymo

fix hourlimit moudle
add attemp times to playerinfo moudle

2024-12-04 09:17 UTC, blueblur0730 requested changes

2024-12-04 09:17 UTC, blueblur0730 commented on archive/server_management/scripting/server_management/player_info.inc
> +	pi_cvMaxTryPlayerInfo 	= CreateConVar("sm_max_try_check_player_time", "5", "Maximum number of attempts to check the played time");
cvar名称建议是和其他风格一致, 避免混淆并且具有辨识度.

2024-12-04 09:17 UTC, blueblur0730 commented on archive/server_management/scripting/server_management/player_info.inc
> +	pi_cvMaxTryPlayerInfo 	= CreateConVar("sm_max_try_check_player_time", "5", "Maximum number of attempts to check the played time");
player_info_try_check_player_time

2024-12-04 09:18 UTC, blueblur0730 commented
关于这个插件可能有些点得说一下.
这个项目本来是已经archive了, 但是最近一段时间我和朋友重新搭建一个服务器并由我进行建设的时候我重新将这个项目翻了出来并做了非常大程度上的修改. 同样在获取玩家时长这方面在我发现Steam Work拓展一次不能获取之后尝试了Rest In Pawn拓展, 同样也是一次获取不到, 所以后面我索性搁置了获取时长的代码 (毕竟没有这个需求). 但这些更改我没有一次提交到github上.
所以我在考虑合并这个pr是否有意义.
如果你想维持现状的话我就直接合并了, 如果你想看到我做的其他更改的话, 那我可以先把现在我用的先上传, 然后你再合并. 粗略地看了下pr没有问题.

2024-12-04 09:23 UTC, blueblur0730 approved these changes

2024-12-05 04:04 UTC, Majestymo commented
佬你可以先上传看看，我主要还是来学习的
![MuaKissGIF](https://github.com/user-attachments/assets/bd8afcaf-e45c-46c4-8a41-042f70314bd7)

2024-12-05 09:36 UTC, merged